// data.js
const data = [
  // Fast Food Category
  {
    id: 1,
    name: "Fast Food A",
    category: "Fast Food", // Category for Fast Food
    rating: 4.5,
    image: "/images/fastfood-a.jpg", // Image URL for the restaurant
    openingTime: "10:00 AM",
    closingTime: "11:00 PM",
    distance: "5 km",
    address: "Location A",
    contact: "123-456-7890",
    cuisine: "American",
    priceRange: "$$",
  },
  {
    id: 2,
    name: "Fast Food B",
    category: "Fast Food",
    rating: 4.0,
    image: "/images/fastfood-b.jpg",
    openingTime: "9:00 AM",
    closingTime: "10:00 PM",
    distance: "7 km",
    address: "Location B",
    contact: "234-567-8901",
    cuisine: "Italian",
    priceRange: "$$",
  },
  {
    id: 3,
    name: "Burger Shack",
    category: "Fast Food",
    rating: 4.7,
    image: "/images/fastfood-c.jpg",
    openingTime: "11:00 AM",
    closingTime: "12:00 AM",
    distance: "6 km",
    address: "Location C",
    contact: "345-678-9012",
    cuisine: "American",
    priceRange: "$",
  },
  {
    id: 4,
    name: "Pizza Town",
    category: "Fast Food",
    rating: 4.2,
    image: "/images/fastfood-d.jpg",
    openingTime: "10:00 AM",
    closingTime: "11:30 PM",
    distance: "8 km",
    address: "Location D",
    contact: "456-789-0123",
    cuisine: "Italian",
    priceRange: "$$$",
  },

  // Non-Veg Category
  {
    id: 5,
    name: "Non-Veg Restaurant A",
    category: "Non-Veg",
    rating: 4.8,
    image: "/images/nonveg-a.jpg",
    openingTime: "8:00 AM",
    closingTime: "10:00 PM",
    distance: "6 km",
    address: "Location E",
    contact: "567-890-1234",
    cuisine: "Indian",
    priceRange: "$$$",
  },
  {
    id: 6,
    name: "The Meat House",
    category: "Non-Veg",
    rating: 4.3,
    image: "/images/nonveg-b.jpg",
    openingTime: "9:00 AM",
    closingTime: "11:00 PM",
    distance: "7 km",
    address: "Location F",
    contact: "678-901-2345",
    cuisine: "Chinese",
    priceRange: "$$",
  },
  {
    id: 7,
    name: "Grilled to Perfection",
    category: "Non-Veg",
    rating: 4.9,
    image: "/images/nonveg-c.jpg",
    openingTime: "10:00 AM",
    closingTime: "10:00 PM",
    distance: "5 km",
    address: "Location G",
    contact: "789-012-3456",
    cuisine: "American",
    priceRange: "$$$",
  },
  {
    id: 8,
    name: "Spicy Grill",
    category: "Non-Veg",
    rating: 4.0,
    image: "/images/nonveg-d.jpg",
    openingTime: "9:30 AM",
    closingTime: "10:30 PM",
    distance: "9 km",
    address: "Location H",
    contact: "890-123-4567",
    cuisine: "Indian",
    priceRange: "$$",
  },

  // Dhabha Category
  {
    id: 9,
    name: "Dhabha A",
    category: "Dhabha",
    rating: 3.8,
    image: "/images/dhabha-a.jpg",
    openingTime: "7:00 AM",
    closingTime: "9:00 PM",
    distance: "4 km",
    address: "Location I",
    contact: "901-234-5678",
    cuisine: "Indian",
    priceRange: "$",
  },
  {
    id: 10,
    name: "Punjabi Dhabha",
    category: "Dhabha",
    rating: 4.2,
    image: "/images/dhabha-b.jpg",
    openingTime: "8:00 AM",
    closingTime: "10:00 PM",
    distance: "10 km",
    address: "Location J",
    contact: "012-345-6789",
    cuisine: "Punjabi",
    priceRange: "$",
  },
  {
    id: 11,
    name: "Dhabha Express",
    category: "Dhabha",
    rating: 4.4,
    image: "/images/dhabha-c.jpg",
    openingTime: "7:30 AM",
    closingTime: "11:00 PM",
    distance: "8 km",
    address: "Location K",
    contact: "123-456-7891",
    cuisine: "Indian",
    priceRange: "$",
  },
  {
    id: 12,
    name: "The Roadside Dhabha",
    category: "Dhabha",
    rating: 4.0,
    image: "/images/dhabha-d.jpg",
    openingTime: "6:00 AM",
    closingTime: "9:30 PM",
    distance: "12 km",
    address: "Location L",
    contact: "234-567-8902",
    cuisine: "Punjabi",
    priceRange: "$",
  },
  
  // Additional Restaurants
  {
    id: 13,
    name: "Tandoori Delight",
    category: "Non-Veg",
    rating: 4.6,
    image: "/images/nonveg-e.jpg",
    openingTime: "8:00 AM",
    closingTime: "10:00 PM",
    distance: "3 km",
    address: "Location M",
    contact: "345-678-9013",
    cuisine: "Indian",
    priceRange: "$$$",
  },
  {
    id: 14,
    name: "Burger King",
    category: "Fast Food",
    rating: 4.3,
    image: "/images/fastfood-e.jpg",
    openingTime: "10:00 AM",
    closingTime: "12:00 AM",
    distance: "10 km",
    address: "Location N",
    contact: "456-789-0124",
    cuisine: "American",
    priceRange: "$$",
  },
  {
    id: 15,
    name: "Pizza Hut",
    category: "Fast Food",
    rating: 4.1,
    image: "/images/fastfood-f.jpg",
    openingTime: "11:00 AM",
    closingTime: "11:00 PM",
    distance: "5 km",
    address: "Location O",
    contact: "567-890-1235",
    cuisine: "Italian",
    priceRange: "$$$",
  },
  {
    id: 16,
    name: "KFC",
    category: "Non-Veg",
    rating: 4.7,
    image: "/images/nonveg-f.jpg",
    openingTime: "10:00 AM",
    closingTime: "11:00 PM",
    distance: "2 km",
    address: "Location P",
    contact: "678-901-2346",
    cuisine: "American",
    priceRange: "$$",
  },
  {
    id: 17,
    name: "Mughlai King",
    category: "Non-Veg",
    rating: 4.5,
    image: "/images/nonveg-g.jpg",
    openingTime: "9:00 AM",
    closingTime: "11:00 PM",
    distance: "7 km",
    address: "Location Q",
    contact: "789-012-3457",
    cuisine: "Indian",
    priceRange: "$$$",
  },
  {
    id: 18,
    name: "Royal Dhabha",
    category: "Dhabha",
    rating: 4.3,
    image: "/images/dhabha-e.jpg",
    openingTime: "8:00 AM",
    closingTime: "10:00 PM",
    distance: "6 km",
    address: "Location R",
    contact: "890-123-4568",
    cuisine: "Punjabi",
    priceRange: "$",
  },
  {
    id: 19,
    name: "Spice Villa",
    category: "Non-Veg",
    rating: 4.2,
    image: "/images/nonveg-h.jpg",
    openingTime: "10:00 AM",
    closingTime: "11:00 PM",
    distance: "9 km",
    address: "Location S",
    contact: "901-234-5679",
    cuisine: "Indian",
    priceRange: "$$",
  },
  {
    id: 20,
    name: "Desi Dhabha",
    category: "Dhabha",
    rating: 3.9,
    image: "/images/dhabha-f.jpg",
    openingTime: "7:00 AM",
    closingTime: "8:00 PM",
    distance: "13 km",
    address: "Location T",
    contact: "012-345-6780",
    cuisine: "Indian",
    priceRange: "$",
  }
];

export default data;
